name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable corepack and prepare Yarn 4
        run: |
          corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check code formatting
        run: yarn format:check

      - name: Run type checking
        run: yarn type-check

      - name: Run linting
        run: yarn lint

      - name: Build application
        run: yarn build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium webkit

      - name: Run Playwright tests
        run: yarn test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-node-${{ matrix.node-version }}
          path: playwright-report/
          retention-days: 7

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-node-${{ matrix.node-version }}
          path: dist/
          retention-days: 7
